---
title: US Health Spending
format: html
---

```{r}
#| label: setup
#| message: false
library(tidyverse)
library(nanoparquet)
library(patchwork)

health_spending <- read_parquet("health_spending.parquet") |> filter(iso3_code == "USA")
financing_schemes <- read_parquet("financing_schemes.parquet") |> filter(iso3_code == "USA")
spending_purpose <- read_parquet("spending_purpose.parquet") |> filter(iso3_code == "USA")
```

## Health spending by funding source

```{r}
#| label: fig-health-spending
#| fig-width: 10
#| fig-height: 4

hs_labels <- c(
  gghed = "Government",
  pvtd = "Private",
  ext = "External"
)

hs <- health_spending |> filter(expenditure_type != "che")

p1 <- hs |>
  ggplot(aes(year, usd2023, fill = expenditure_type)) +
  geom_area() +
  scale_fill_brewer(palette = "Set2", labels = hs_labels) +
  scale_y_continuous(labels = scales::label_dollar(scale = 1e-9, suffix = "B")) +
  labs(x = NULL, y = "Spending (2023 USD)", fill = NULL)

p2 <- hs |>
  ggplot(aes(year, che, fill = expenditure_type)) +
  geom_area() +
  scale_fill_brewer(palette = "Set2", labels = hs_labels) +
  scale_y_continuous(labels = scales::label_percent(scale = 1)) +
  labs(x = NULL, y = "% of CHE", fill = NULL)

p1 + p2 + plot_layout(guides = "collect") & theme(legend.position = "bottom")
```

## Health spending by financing scheme

```{r}
#| label: fig-financing-schemes
#| fig-width: 10
#| fig-height: 4

fs_labels <- c(
  hf1 = "Govt/compulsory",
  hf2 = "Voluntary",
  hf3 = "Out-of-pocket",
  hf4 = "Non-resident",
  hfnec = "Unspecified"
)

p1 <- financing_schemes |>
  ggplot(aes(year, usd2023, fill = financing_scheme)) +
  geom_area() +
  scale_fill_brewer(palette = "Set2", labels = fs_labels) +
  scale_y_continuous(labels = scales::label_dollar(scale = 1e-9, suffix = "B")) +
  labs(x = NULL, y = "Spending (2023 USD)", fill = NULL)

p2 <- financing_schemes |>
  ggplot(aes(year, che, fill = financing_scheme)) +
  geom_area() +
  scale_fill_brewer(palette = "Set2", labels = fs_labels) +
  scale_y_continuous(labels = scales::label_percent(scale = 1)) +
  labs(x = NULL, y = "% of CHE", fill = NULL)

p1 + p2 + plot_layout(guides = "collect") & theme(legend.position = "bottom")
```

## Health spending by purpose

```{r}
#| label: fig-spending-purpose
#| fig-width: 10
#| fig-height: 4

sp_labels <- c(
  hc1 = "Curative",
  hc2 = "Rehabilitative",
  hc3 = "Long-term",
  hc4 = "Ancillary",
  hc5 = "Medical goods",
  hc6 = "Preventive",
  hc7 = "Governance",
  hc9 = "Other"
)

p1 <- spending_purpose |>
  ggplot(aes(year, usd2023, fill = spending_purpose)) +
  geom_area() +
  scale_fill_brewer(palette = "Set2", labels = sp_labels) +
  scale_y_continuous(labels = scales::label_dollar(scale = 1e-9, suffix = "B")) +
  labs(x = NULL, y = "Spending (2023 USD)", fill = NULL)

p2 <- spending_purpose |>
  ggplot(aes(year, che, fill = spending_purpose)) +
  geom_area() +
  scale_fill_brewer(palette = "Set2", labels = sp_labels) +
  scale_y_continuous(labels = scales::label_percent(scale = 1)) +
  labs(x = NULL, y = "% of CHE", fill = NULL)

p1 + p2 + plot_layout(guides = "collect") & theme(legend.position = "bottom")
```
